### ISSUE TITLE
Bug - AshUUID will not compile if resource has reference to itself

### ISSUE THREAD

**Issue by sezaru** [zoonect-oss/ash_uuid#1]
If you have a resource with a relationship to itself, `ash_uuid` will fail to compile for that resource.

For example, if I have this resource:

```elixir
defmodule FeedbackCupcake.Feedbacks.Template do
  use Ash.Resource,
    data_layer: AshPostgres.DataLayer,
    extensions: [ AshUUID]

  attributes do
    uuid_attribute :id
  end

  relationships do
    belongs_to :from_template, FeedbackCupcake.Feedbacks.Template do
      allow_nil? true
      attribute_writable? true
    end
  end

  postgres do
    table "templates"

    repo FeedbackCupcake.Repo
  end
end
```

Will give the following error:

```
[sezdocs@fedora feedback_cupcake]$ mix compile
Compiling 5 files (.ex)

== Compilation error in file lib/feedback_cupcake/feedbacks/template.ex ==
** (RuntimeError) Exception in transformer AshUUID.Transformers.BelongsToAttribute on FeedbackCupcake.Feedbacks.Template: 

function FeedbackCupcake.Feedbacks.Template.spark_dsl_config/0 is undefined (module FeedbackCupcake.Feedbacks.Template is not available)
    FeedbackCupcake.Feedbacks.Template.spark_dsl_config()
    (ash_uuid 0.2.2) lib/ash_uuid/transformers/belongs_to_attribute.ex:21: anonymous fn/2 in AshUUID.Transformers.BelongsToAttribute.transform/1
    (elixir 1.15.4) lib/enum.ex:4393: Enum.reject_list/2
    (elixir 1.15.4) lib/enum.ex:4396: Enum.reject_list/2
    (ash_uuid 0.2.2) lib/ash_uuid/transformers/belongs_to_attribute.ex:15: AshUUID.Transformers.BelongsToAttribute.transform/1
    (spark 1.1.22) lib/spark/dsl/extension.ex:679: anonymous fn/4 in Spark.Dsl.Extension.run_transformers/4
    (elixir 1.15.4) lib/enum.ex:4830: Enumerable.List.reduce/3
    /run/host/home/sezdocs/projects/feedback_cupcake/lib/feedback_cupcake/feedbacks/template.ex:1: (file)
```

**Comment by moissela** [comment]
This issue should be resolved in v0.3.0 just released.

Thanks for the feedback @sezaru let me know if it works as expected 😉
