### ISSUE TITLE
Embedded resource can't be inserted into resource when using AshUUID

### ISSUE THREAD

**Issue by sezaru** [zoonect-oss/ash_uuid#4]
I have the following embedded resource:

```elixir
defmodule FeedbackCupcake.Feedbacks.Student.Image do
  use Ash.Resource,
    data_layer: :embedded,
   extensions: [AshUUID]

  code_interface do
    define_for FeedbackCupcake.Feedbacks

    define :new
  end

  attributes do
    uuid_attribute :id

    attribute :url, :string, allow_nil?: false
    attribute :type, :string, allow_nil?: false

    attribute :s3_path, :string, allow_nil?: false, private?: true
  end

  actions do
    create :new do
      primary? true

      argument :s3_path, :string, allow_nil?: false

      change set_attribute(:s3_path, arg(:s3_path))
    end
  end
end
```

This resource is used in another resource with the following attribute: `attribute :image, Image`.

When I try to create a new resource with the Image resource, it will fail when postgrex tries to convert it to jsonb:

```
     ** (Ash.Error.Unknown) Unknown Error
     
     Context: resolving data on perform FeedbackCupcake.Feedbacks.Student.create
     * Context: resolving data on perform FeedbackCupcake.Feedbacks.Student.create
     
     ** (Jason.EncodeError) invalid byte 0x8A in <<1, 138, 16, 217, 172, 234, 119, 11, 141, 134, 107, 158, 18, 36, 48, 209>>
       (jason 1.4.1) lib/jason.ex:213: Jason.encode_to_iodata!/2
       deps/postgrex/lib/postgrex/type_module.ex:947: FeedbackCupcake.PostgresTypes.encode_params/3
       (postgrex 0.17.2) lib/postgrex/query.ex:75: DBConnection.Query.Postgrex.Query.encode/3
       (db_connection 2.5.0) lib/db_connection.ex:1323: DBConnection.encode/5
       (db_connection 2.5.0) lib/db_connection.ex:1423: DBConnection.run_prepare_execute/5
       (db_connection 2.5.0) lib/db_connection.ex:656: DBConnection.parsed_prepare_execute/5
       (db_connection 2.5.0) lib/db_connection.ex:648: DBConnection.prepare_execute/4
       (postgrex 0.17.2) lib/postgrex.ex:340: Postgrex.query/4
       (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:955: Ecto.Adapters.SQL.struct/10
       (ecto 3.10.3) lib/ecto/repo/schema.ex:764: Ecto.Repo.Schema.apply/4
       (ecto 3.10.3) lib/ecto/repo/schema.ex:377: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
       (feedback_cupcake 0.1.0) lib/feedback_cupcake/repo.ex:4: FeedbackCupcake.Repo.insert/2
       (ash_postgres 1.3.41) lib/data_layer.ex:1242: AshPostgres.DataLayer.create/2
       (ash 2.14.2) lib/ash/actions/create/create.ex:438: anonymous fn/8 in Ash.Actions.Create.as_requests/5
       (ash 2.14.2) lib/ash/changeset/changeset.ex:2110: Ash.Changeset.run_around_actions/2
       (ash 2.14.2) lib/ash/changeset/changeset.ex:1757: anonymous fn/2 in Ash.Changeset.with_hooks/3
       (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:1203: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
       (db_connection 2.5.0) lib/db_connection.ex:1630: DBConnection.run_transaction/4
       (ash 2.14.2) lib/ash/changeset/changeset.ex:1755: anonymous fn/3 in Ash.Changeset.with_hooks/3
       (ash 2.14.2) lib/ash/changeset/changeset.ex:1871: anonymous fn/2 in Ash.Changeset.transaction_hooks/2
```

I did some digging, and noticed that the `:id` field is being sent to `AshUUID.UUID.dump_to_native/2` where it will be converted into a binary format:

```elixir
[(ash_uuid 0.4.0) lib/ash_uuid/uuid.ex:46: AshUUID.UUID.dump_to_native/2]
term #=> "02u5UVzC3PGKrfNS0Jl1Af"

[(ash_uuid 0.4.0) lib/ash_uuid/uuid.ex:47: AshUUID.UUID.dump_to_native/2]
constraints #=> [
  prefix: "image",
  version: 7,
  encoded?: true,
  prefixed?: false,
  migration_default?: true
]

[(ash_uuid 0.4.0) lib/ash_uuid/uuid.ex:48: AshUUID.UUID.dump_to_native/2]
process(term, constraints[:prefix], initial_format(term), :integer) #=> {:ok,
 <<1, 138, 16, 217, 172, 234, 119, 11, 141, 134, 107, 158, 18, 36, 48, 209>>}
```

After that, the full map will be sent to postgrex which will use `Jason.encode_to_iodata!/2` to create the `jsonb` result, the map that `Postgrex.Extensions.JSONB` will receive is this:

```elixir
map #=> %{
  id: <<1, 138, 16, 217, 172, 234, 119, 11, 141, 134, 107, 158, 18, 36, 48,
    209>>,
  type: "image type",
  url: "image url",
  s3_path: "image s3 path"
}
```

As you can see, the id is sent as a binary, and because of that, Jason can't convert it into a jsonb and will fail.

**Comment by moissela** [comment]
This issue should be resolved in v0.5.0 just released.

Thanks for the feedback @sezaru and let me know if it works as expected 😉
